### ISSUE TITLE
CSVDataset

### ISSUE THREAD

**Issue by hassiahk** [Quick-AI/quickvision#35]
## 🐛 Bug
The current `CSVDataset` will not work until and unless we make changes as I described in the issue of `pytorch_cnn_training`. Should I make changes and send a PR for this?

**Comment by oke-aditya** [comment]
Yes ! The datasets are next on tasks. We need tests as well which would be really nice. PR is welcome

**Comment by hassiahk** [comment]
I have never written tests before so if you can provide a template or an example that I can look at, would be really great. In the meanwhile, I will fix the changes and send a PR. :smile:

**Comment by oke-aditya** [comment]
For tests we use unittest. You can have a look at the tests folder. 

What possibly you can do is create a CSV with such data format. 

Process it using your own dataset

Assert it to torch.utils.Dataset and try to so a `sanity_fit()` of model.

**Comment by oke-aditya** [comment]
You can simply use 2 dummy images.

Also I propose you to pitch a dream API. 


How your dataset will work and what is the I/P and O/p format

**Comment by hassiahk** [comment]
We can use torch 1.7 right? Because `torch` is not in the `requirements.txt`
