### ISSUE TITLE
Code formatting and linting

### ISSUE THREAD

**Issue by hassiahk** [Quick-AI/quickvision#36]
Are we currently using any code formatting packages (`black`, `autopep8`) and linting packages (`pylint`)?

**Comment by oke-aditya** [comment]
Well yes. We are using `flake8` for litning which also checks for PEP8 formatting. Which will be checked for PR over CI. 

Don't worry these checks are done very easily using CI.

**Comment by hassiahk** [comment]
Yes, but I need to write code according to the formatters, or else the CI tests will fail, right. That's why I asked. :smile:

**Comment by oke-aditya** [comment]
Don't worry about CI failing for fomatting. These can be super easily fixed.
Linting doesn't cause failure to others Tests CIs, so don't worry about that.
