### ISSUE TITLE
create_cifar10_dataset and create_loaders

### ISSUE THREAD

**Issue by hassiahk** [Quick-AI/quickvision#41]
## 🚀 Feature
Are we not going to include `create_cifar10_dataset` and `create_loaders` like in `pytorch_cnn_training`? Or is there a plan to include them later on? I think these are pretty handy to have.

I saw these were only getting used in `tests`.

**Comment by oke-aditya** [comment]
It is useful but it abstracts code over torch and is like reinventing wheel. 


Hence I kept it in examples and not to confuse users. It is useful in testing though.

**Comment by oke-aditya** [comment]
It is useful but it abstracts code over torch and is like reinventing wheel. 


Hence I kept it in examples and not to confuse users. It is useful in testing though.

**Comment by hassiahk** [comment]
Yes, that makes sense.
