### ISSUE TITLE
Retina Net

### ISSUE THREAD

**Issue by oke-aditya** [Quick-AI/quickvision#6]
## 🚀 Feature

Our second detection model

The following needs to be done.

- [x] Support all torchvision backbones.
- [x] FPN Support for Resnet Backbones.
- [x] Support for negative samples etc.
- [x] Mixed Precision Training.
- [x] `train_step, val_step, fit ` APIs
- [ ] Sanity Fit API
- [x] IoU, MaP calculations while training and testing.
- [x] Lightning Trainer.

**Comment by ramaneswaran** [comment]
Looks like most of the work here is done
I will give sanity fit functions a shot

**Comment by oke-aditya** [comment]
Nice. We need slight refactor with detection models, but that will not affect sanity fit API.
