### ISSUE TITLE
[RFC] Drop Vision Name and PascalCase Classes

### ISSUE THREAD

**Issue by oke-aditya** [Quick-AI/quickvision#89]
## 🚀 Feature

Drop the names as VisionFasterRCNN, VisionCNN, let's call it CNN, Faster RCNN

### Motivation

Why have the abstraction for Vision ...

### Pitch

Replace these all names, and remove vision.
It's a breaking change and hence delayed to `0.2.0`

### Alternatives

Let stuff stay as it is. :package:

**Comment by hassiahk** [comment]
I don't mind keeping it like this.

**Comment by oke-aditya** [comment]
Also we should `PascalCase` the classes as a standard Python convention all over the library.
